version: '2'
services:

    gunicorn:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 1 app:app -b :8000
    
    gunicorn_multiple:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        container_name: 'gunicorn_3_workers'
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 3 app:app -b :8000

    replica_gunicorn_1:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        container_name: 'replica_gunicorn_1'
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 1 app:app -b :8000

    replica_gunicorn_2:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        container_name: 'replica_gunicorn_2'
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 1 app:app -b :8000

    replica_gunicorn_3:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        container_name: 'replica_gunicorn_3'
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 1 app:app -b :8000

    node:
        build:
            context: .
            dockerfile: node-express.dockerfile
        volumes:
            - ./js/src:/app/src
        links:
            - grafana
        command: npm run start

    replica_node_1:
        build:
            context: .
            dockerfile: node-express.dockerfile
        container_name: 'replica_node_1'
        volumes:
            - ./js/src:/app/src
        links:
            - grafana
        command: npm run start

    replica_node_2:
        build:
            context: .
            dockerfile: node-express.dockerfile
        container_name: 'replica_node_2'
        volumes:
            - ./js/src:/app/src
        links:
            - grafana
        command: npm run start

    replica_node_3:
        build:
            context: .
            dockerfile: node-express.dockerfile
        container_name: 'replica_node_3'
        volumes:
            - ./js/src:/app/src
        links:
            - grafana
        command: npm run start

    nginx:
        image: nginx:1.13.10
        container_name: 'nginx'
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - gunicorn
            - replica_gunicorn_1
            - replica_gunicorn_2
            - replica_gunicorn_3
            - node
            - replica_node_1
            - replica_node_2
            - replica_node_3

    graphite:
        image: graphiteapp/graphite-statsd:1.1.3
        container_name: 'graphite'
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:5.0.4
        container_name: 'grafana'
        ports:
            - "80:3000"

    cadvisor:
        image: google/cadvisor:v0.27.4
        container_name: 'cadvisor'
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
