{
 "title": "Dashboard General",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "arquitectura-tp_gunicorn_1, arquitectura-tp_node_1, gunicorn_multiple, nginx"
   },
   {
    "name": "replic_1",
    "query": "replica_node_1, replica_node_2, replica_node_3, replica_gunicorn_1, replica_gunicorn_2, replica_gunicorn_3"
   },
   {
    "name": "replic_2",
    "query": "replica_node_1, replica_node_2, replica_node_3, replica_gunicorn_1, replica_gunicorn_2, replica_gunicorn_3"
   },
   {
    "name": "replic_3",
    "query": "replica_node_1, replica_node_2, replica_node_3, replica_gunicorn_1, replica_gunicorn_2, replica_gunicorn_3"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Load Balancer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.gauges.cadvisor.$container.cpu_cumulative_usage), 1e-8)"
    }
   ]
  },
  {
   "title": "CPU Container 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.gauges.cadvisor.$replic_1.cpu_cumulative_usage), 1e-8)"
    }
   ]
  },
  {
   "title": "CPU Container 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.gauges.cadvisor.$replic_2.cpu_cumulative_usage), 1e-8)"
    }
   ]
  },
  {
   "title": "CPU Container 3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.gauges.cadvisor.$replic_3.cpu_cumulative_usage), 1e-8)"
    }
   ]
  },
  {
   "title": "Memory Usage Loadbalancer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.$container.memory_usage"
    }
   ]
  },
  {
   "title": "Memory Usage Container 1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.$replic_1.memory_usage"
    }
   ]
  },
  {
   "title": "Memory Usage Container 2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.$replic_2.memory_usage"
    }
   ]
  },
  {
   "title": "Memory Usage Container 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.$replic_3.memory_usage"
    }
   ]
  },
  {
   "title": "Network Usage Loadbalancer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.$container.rx_bytes)"
    },
    {
     "target": "derivative(stats.gauges.cadvisor.$container.tx_bytes)"
    }
   ]
  },
  {
   "title": "Network Usage Container 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.$replic_1.rx_bytes)"
    },
    {
     "target": "derivative(stats.gauges.cadvisor.$replic_1.tx_bytes)"
    }
   ]
  },
  {
   "title": "Network Usage Container 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.$replic_2.rx_bytes)"
    },
    {
     "target": "derivative(stats.gauges.cadvisor.$replic_2.tx_bytes)"
    }
   ]
  },
  {
   "title": "Network Usage Container 3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.$replic_3.rx_bytes)"
    },
    {
     "target": "derivative(stats.gauges.cadvisor.$replic_3.tx_bytes)"
    }
   ]
  }
 ]
}