{
 "title": "Dashboard General",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage Node vs Flask",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.gauges.cadvisor.tp-arq-docker_gunicorn_1.cpu_cumulative_usage), 1e-8)"
    },
    {
     "target": "scale(derivative(stats.gauges.cadvisor.tp-arq-docker_node_1.cpu_cumulative_usage), 1e-8)"
    }
   ]
  },
  {
   "title": "Memory Usage Flask App vs Express App",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.tp-arq-docker_gunicorn_1.memory_usage"
    },
    {
     "target": "stats.gauges.cadvisor.tp-arq-docker_node_1.memory_usage"
    }
   ]
  },
  {
   "title": "Node Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.tp-arq-docker_node_1.rx_bytes"
    },
    {
     "target": "stats.gauges.cadvisor.tp-arq-docker_node_1.tx_bytes"
    }
   ]
  },
  {
   "title": "Gunicorn Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.tp-arq-docker_gunicorn_1.tx_bytes"
    },
    {
     "target": "stats.gauges.cadvisor.tp-arq-docker_gunicorn_1.rx_bytes"
    }
   ]
  }
 ]
}