{
 "title": "Dashboard General",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "arquitectura-tp_gunicorn_1, arquitectura-tp_node_1, gunicorn_3_workers"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "target": "scale(derivative(stats.gauges.cadvisor.$container.cpu_cumulative_usage), 1e-8)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "target": "stats.gauges.cadvisor.$container.memory_usage"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.$container.rx_bytes)"
    },
    {
     "target": "derivative(stats.gauges.cadvisor.$container.tx_bytes)"
    }
   ]
  }
 ]
}